//! The workspace context digest behind `wsx context show|write`.
//!
//! An editor-hosted agent (one that runs inside the user's editor rather
//! than in a wsx-spawned PTY) has no way to learn what this workspace is
//! for, what its primary agent last reported, or who its peers are. This
//! module renders all of that as one markdown file the editor can hand to
//! its agent as context. `gather` reads the store, git, and the primary
//! agent's transcript; `render` is pure so the format is unit-tested
//! without any of those.

use crate::config::Dirs;
use crate::data::agents::AgentInstance;
use crate::data::store::{ReportedStatus, Store, Workspace, WorkspaceRecap};
use crate::error::Result;
use std::path::{Path, PathBuf};

/// Hard cap on the primary agent's last message, in chars.
pub const MAX_LAST_MESSAGE_CHARS: usize = 2000;
/// Hard cap on the recent-commits list.
pub const MAX_COMMITS: usize = 20;

#[derive(Debug, Clone)]
pub struct ContextDigest {
    pub repo_name: String,
    pub workspace_name: String,
    pub branch: String,
    pub base_ref: String,
    pub worktree: PathBuf,
    /// Primary first, then creation order (the store's ordering).
    pub agents: Vec<AgentInstance>,
    pub status: Option<ReportedStatus>,
    pub recap: Option<WorkspaceRecap>,
    /// `"<sha> <subject>"` lines, newest first, already capped.
    pub commits: Vec<String>,
    /// `None` when git status could not be read.
    pub uncommitted: Option<crate::git::WorkspaceStatus>,
    /// Untruncated; `render` applies the cap.
    pub last_assistant_text: Option<String>,
    /// Injected so age strings are deterministic in tests.
    pub now_ms: i64,
}

const INSTRUCTIONS_HEADER: &str = "## External instructions";

fn instructions(primary_label: &str) -> String {
    format!(
        "You are an editor-hosted agent working inside a wsx-managed worktree. The \
agents listed above share this branch and this working tree with you, and one \
of them (the primary) owns this workspace's status and recap.\n\
\n\
- Before editing, run `git status` and `git diff`; the primary agent may have \
changed files since this digest was written.\n\
- Keep edits small and scoped. Do not create branches, rename the workspace, or \
run `wsx status set` / `wsx recap set`; those belong to the primary agent.\n\
- When you finish a change, or when you need a decision the primary agent \
should make, report it with:\n  \
`wsx agent send {primary_label} \"<one-paragraph summary>\"`\n  \
Run it from this worktree; the workspace is resolved from cwd.\n\
- This file is regenerated by `wsx context write`; do not edit it.\n"
    )
}

/// Coarse age: `Ns ago` / `Nm ago` / `Nh ago` / `Nd ago`. Negative
/// differences (clock skew) clamp to zero.
pub fn format_age(now_ms: i64, then_ms: i64) -> String {
    let secs = (now_ms - then_ms).max(0) / 1000;
    match secs {
        s if s < 60 => format!("{s}s ago"),
        s if s < 3_600 => format!("{}m ago", s / 60),
        s if s < 86_400 => format!("{}h ago", s / 3_600),
        s => format!("{}d ago", s / 86_400),
    }
}

fn truncate_chars(s: &str, max: usize) -> String {
    if s.chars().count() <= max {
        return s.to_string();
    }
    let mut out: String = s.chars().take(max).collect();
    out.push_str("… [truncated]");
    out
}

/// Fill a digest for `ws`. Store reads propagate errors (the DB is the
/// one thing we cannot render without); git and transcript failures
/// degrade to `None` / empty so the digest never fails on a dirty or
/// missing worktree.
pub async fn gather(store: &Store, ws: &Workspace) -> Result<ContextDigest> {
    let repo_name = store
        .repos()?
        .into_iter()
        .find(|r| r.id == ws.repo_id)
        .map(|r| r.name)
        .unwrap_or_else(|| "?".to_string());
    let agents = store.workspace_agents(ws.id)?;
    let status = store.workspace_status(ws.id)?;
    let recap = store.workspace_recap(ws.id)?;

    let worktree = ws.worktree_path.clone();
    let worktree_exists = worktree.is_dir();

    let base_ref = if worktree_exists {
        crate::git::resolve_base_branch(&worktree).await
    } else {
        "main".to_string()
    };
    let commits = if worktree_exists {
        crate::git::log_oneline(&worktree, &base_ref, MAX_COMMITS)
            .await
            .unwrap_or_default()
    } else {
        Vec::new()
    };
    let uncommitted = if worktree_exists {
        crate::git::workspace_status(&worktree).await.ok()
    } else {
        None
    };

    let primary_kind = agents
        .iter()
        .find(|a| a.is_primary)
        .map(|a| a.agent)
        .unwrap_or(ws.agent);
    let last_assistant_text = if worktree_exists {
        last_assistant_text(primary_kind, &worktree)
    } else {
        None
    };

    Ok(ContextDigest {
        repo_name,
        workspace_name: ws.name.clone(),
        branch: ws.branch.clone(),
        base_ref,
        worktree,
        agents,
        status,
        recap,
        commits,
        uncommitted,
        last_assistant_text,
        now_ms: crate::data::store::now_ms(),
    })
}

/// Whole-transcript scan for the primary agent's most recent assistant
/// text. Any failure (no session, parse error) is `None`; the digest is
/// advisory and must not fail because a log is mid-write.
fn last_assistant_text(kind: crate::pty::session::AgentKind, worktree: &Path) -> Option<String> {
    let file = crate::activity::locate_session_file_for(kind, worktree)?;
    match crate::activity::tail_session_for(kind, &file, 0) {
        Ok(update) => update.last_assistant_text,
        Err(e) => {
            tracing::debug!(?file, error = %e, "context digest: transcript tail failed");
            None
        }
    }
}

pub fn render(d: &ContextDigest) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "# wsx workspace: {}/{}\n\n",
        d.repo_name, d.workspace_name
    ));
    out.push_str(&format!("- branch: {} (base: {})\n", d.branch, d.base_ref));
    out.push_str(&format!("- worktree: {}\n", d.worktree.display()));

    let agents = if d.agents.is_empty() {
        "-".to_string()
    } else {
        d.agents
            .iter()
            .map(|a| {
                if a.is_primary {
                    format!("{} (primary)", a.label())
                } else {
                    a.label()
                }
            })
            .collect::<Vec<_>>()
            .join(", ")
    };
    out.push_str(&format!("- agents: {agents}\n"));

    let status = match &d.status {
        None => "-".to_string(),
        Some(s) => {
            let age = format_age(d.now_ms, s.reported_at);
            match s.message.as_deref().filter(|m| !m.trim().is_empty()) {
                Some(m) => format!("{} — \"{}\" ({}, {})", s.state.as_str(), m, s.source, age),
                None => format!("{} ({}, {})", s.state.as_str(), s.source, age),
            }
        }
    };
    out.push_str(&format!("- status: {status}\n"));

    if let Some(r) = &d.recap {
        let f = |v: &Option<String>| v.as_deref().unwrap_or("-").to_string();
        out.push_str("\n## Recap\n\n");
        out.push_str(&format!("- goal: {}\n", f(&r.goal)));
        out.push_str(&format!("- state: {}\n", f(&r.state)));
        out.push_str(&format!("- next: {}\n", f(&r.next)));
    }

    if !d.commits.is_empty() {
        out.push_str(&format!("\n## Recent commits ({}..HEAD)\n\n", d.base_ref));
        for line in d.commits.iter().take(MAX_COMMITS) {
            out.push_str(&format!("- {line}\n"));
        }
    }
    if let Some(u) = &d.uncommitted {
        let summary = if u.modified == 0 && u.untracked == 0 {
            "clean".to_string()
        } else {
            format!("{} modified, {} untracked", u.modified, u.untracked)
        };
        out.push_str(&format!("\nUncommitted: {summary}\n"));
    }

    if let Some(text) = d
        .last_assistant_text
        .as_deref()
        .map(str::trim)
        .filter(|t| !t.is_empty())
    {
        out.push_str("\n## Primary agent's last message\n\n");
        out.push_str(&truncate_chars(text, MAX_LAST_MESSAGE_CHARS));
        out.push('\n');
    }

    let primary_label = d
        .agents
        .iter()
        .find(|a| a.is_primary)
        .map(|a| a.label())
        .unwrap_or_else(|| "primary".to_string());
    out.push_str(&format!("\n{INSTRUCTIONS_HEADER}\n\n"));
    out.push_str(&instructions(&primary_label));
    out
}

pub fn digest_path(dirs: &Dirs, repo_name: &str, workspace_name: &str) -> PathBuf {
    dirs.context_dir()
        .join(repo_name)
        .join(format!("{workspace_name}.md"))
}

/// Write via a sibling temp file + rename so a concurrent reader never
/// observes a partial digest.
pub fn write_atomic(path: &Path, contents: &str) -> std::io::Result<()> {
    let parent = path.parent().ok_or_else(|| {
        std::io::Error::new(
            std::io::ErrorKind::InvalidInput,
            "digest path has no parent",
        )
    })?;
    std::fs::create_dir_all(parent)?;
    let file_name = path
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("digest.md");
    let tmp = parent.join(format!(
        ".{file_name}.{}.{}.tmp",
        std::process::id(),
        rand::random::<u32>()
    ));
    std::fs::write(&tmp, contents)?;
    match std::fs::rename(&tmp, path) {
        Ok(()) => Ok(()),
        Err(e) => {
            let _ = std::fs::remove_file(&tmp);
            Err(e)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::data::store::{AgentInstanceId, ReportedState, WorkspaceId};
    use crate::pty::session::AgentKind;

    fn agent(kind: AgentKind, ordinal: i64, primary: bool) -> AgentInstance {
        AgentInstance {
            id: AgentInstanceId(ordinal),
            workspace_id: WorkspaceId(1),
            agent: kind,
            ordinal,
            is_primary: primary,
            session_ref: None,
            created_at: 0,
        }
    }

    fn full() -> ContextDigest {
        ContextDigest {
            repo_name: "workspacex".into(),
            workspace_name: "editor-agent-context".into(),
            branch: "bakedbean/editor-agent-context".into(),
            base_ref: "origin/main".into(),
            worktree: PathBuf::from("/tmp/wt"),
            agents: vec![
                agent(AgentKind::Claude, 1, true),
                agent(AgentKind::Claude, 2, false),
            ],
            status: Some(ReportedStatus {
                state: ReportedState::Working,
                message: Some("writing the spec".into()),
                source: "claude".into(),
                reported_at: 1_000_000 - 4 * 60 * 1000,
            }),
            recap: Some(WorkspaceRecap {
                goal: Some("Add wsx context".into()),
                state: Some("spec approved".into()),
                next: Some("write plan".into()),
                goal_short: Some("ctx".into()),
                state_short: None,
                next_short: None,
                updated_at: 0,
            }),
            commits: vec![
                "ff2a9ad fix(input): swallow Ctrl-D".into(),
                "801794a fix(status): stop Idle".into(),
            ],
            uncommitted: Some(crate::git::WorkspaceStatus {
                modified: 3,
                untracked: 1,
                ahead: 0,
                behind: 0,
            }),
            last_assistant_text: Some("I finished the spec.".into()),
            now_ms: 1_000_000,
        }
    }

    fn minimal() -> ContextDigest {
        ContextDigest {
            repo_name: "r".into(),
            workspace_name: "w".into(),
            branch: "b/w".into(),
            base_ref: "main".into(),
            worktree: PathBuf::from("/tmp/wt"),
            agents: vec![],
            status: None,
            recap: None,
            commits: vec![],
            uncommitted: None,
            last_assistant_text: None,
            now_ms: 0,
        }
    }

    #[test]
    fn full_digest_renders_every_section_in_order() {
        let out = render(&full());
        let idx = |needle: &str| {
            out.find(needle)
                .unwrap_or_else(|| panic!("missing {needle:?}\n{out}"))
        };
        assert!(out.starts_with("# wsx workspace: workspacex/editor-agent-context\n"));
        assert!(out.contains("- branch: bakedbean/editor-agent-context (base: origin/main)\n"));
        assert!(out.contains("- worktree: /tmp/wt\n"));
        assert!(out.contains("- agents: claude (primary), claude#2\n"));
        assert!(out.contains("- status: working — \"writing the spec\" (claude, 4m ago)\n"));
        assert!(out.contains(
            "## Recap\n\n- goal: Add wsx context\n- state: spec approved\n- next: write plan\n"
        ));
        assert!(out.contains("## Recent commits (origin/main..HEAD)\n\n- ff2a9ad fix(input): swallow Ctrl-D\n- 801794a fix(status): stop Idle\n\nUncommitted: 3 modified, 1 untracked\n"));
        assert!(out.contains("## Primary agent's last message\n\nI finished the spec.\n"));
        assert!(out.contains("## External instructions\n"));
        assert!(out.contains("`wsx agent send claude \"<one-paragraph summary>\"`"));
        assert!(idx("## Recap") < idx("## Recent commits"));
        assert!(idx("## Recent commits") < idx("## Primary agent's last message"));
        assert!(idx("## Primary agent's last message") < idx("## External instructions"));
        assert!(out.ends_with('\n'));
    }

    #[test]
    fn minimal_digest_omits_optional_sections_and_uses_dashes() {
        let out = render(&minimal());
        assert!(out.contains("- agents: -\n"));
        assert!(out.contains("- status: -\n"));
        assert!(!out.contains("## Recap"));
        assert!(!out.contains("## Recent commits"));
        assert!(!out.contains("Uncommitted:"));
        assert!(!out.contains("## Primary agent's last message"));
        assert!(out.contains("## External instructions\n"));
        // No primary → the generic `primary` address, which `wsx agent send` accepts.
        assert!(out.contains("`wsx agent send primary \"<one-paragraph summary>\"`"));
    }

    #[test]
    fn recap_missing_fields_render_dashes() {
        let mut d = minimal();
        d.recap = Some(WorkspaceRecap {
            goal: Some("g".into()),
            ..Default::default()
        });
        let out = render(&d);
        assert!(out.contains("- goal: g\n- state: -\n- next: -\n"));
    }

    #[test]
    fn status_without_message_omits_quote() {
        let mut d = minimal();
        d.status = Some(ReportedStatus {
            state: ReportedState::Blocked,
            message: None,
            source: "hook".into(),
            reported_at: 0,
        });
        d.now_ms = 2 * 3600 * 1000;
        assert!(render(&d).contains("- status: blocked (hook, 2h ago)\n"));
    }

    #[test]
    fn clean_tree_says_clean_and_git_failure_omits_line() {
        let mut d = full();
        d.uncommitted = Some(crate::git::WorkspaceStatus::default());
        assert!(render(&d).contains("Uncommitted: clean\n"));
        d.uncommitted = None;
        assert!(!render(&d).contains("Uncommitted:"));
    }

    #[test]
    fn commits_section_omitted_when_empty_but_uncommitted_line_stays() {
        let mut d = full();
        d.commits.clear();
        let out = render(&d);
        assert!(!out.contains("## Recent commits"));
        assert!(out.contains("\nUncommitted: 3 modified, 1 untracked\n"));
    }

    #[test]
    fn last_message_truncates_on_char_boundary() {
        let mut d = full();
        // 1999 ASCII chars + one 4-byte char + more: the cut must land on a
        // char boundary, keep exactly MAX chars, and append the marker.
        let mut text = "a".repeat(MAX_LAST_MESSAGE_CHARS - 1);
        text.push('😀');
        text.push_str(&"b".repeat(50));
        d.last_assistant_text = Some(text);
        let out = render(&d);
        let section = out
            .split("## Primary agent's last message\n\n")
            .nth(1)
            .unwrap()
            .split("\n\n## External instructions")
            .next()
            .unwrap();
        assert!(section.ends_with("… [truncated]"), "{section}");
        let body = section.trim_end_matches("… [truncated]");
        assert_eq!(body.chars().count(), MAX_LAST_MESSAGE_CHARS);
        assert!(body.ends_with('😀'));
    }

    #[test]
    fn last_message_at_cap_is_not_truncated() {
        let mut d = full();
        d.last_assistant_text = Some("x".repeat(MAX_LAST_MESSAGE_CHARS));
        assert!(!render(&d).contains("[truncated]"));
    }

    #[test]
    fn instructions_never_name_an_editor() {
        let out = render(&full()).to_lowercase();
        assert!(!out.contains("neovim") && !out.contains("nvim") && !out.contains("magenta"));
    }

    #[test]
    fn format_age_buckets() {
        assert_eq!(format_age(10_000, 0), "10s ago");
        assert_eq!(format_age(4 * 60_000, 0), "4m ago");
        assert_eq!(format_age(2 * 3_600_000, 0), "2h ago");
        assert_eq!(format_age(3 * 86_400_000, 0), "3d ago");
        assert_eq!(format_age(0, 5_000), "0s ago"); // clock skew clamps to zero
    }

    #[test]
    fn digest_path_nests_repo_then_workspace() {
        let dir = tempfile::TempDir::new().unwrap();
        let dirs = Dirs::for_test(dir.path());
        assert_eq!(
            digest_path(&dirs, "workspacex", "cozy-primrose"),
            dir.path().join("wsx/context/workspacex/cozy-primrose.md")
        );
    }

    #[test]
    fn write_atomic_creates_parents_and_leaves_no_temp_file() {
        let dir = tempfile::TempDir::new().unwrap();
        let target = dir.path().join("a/b/c.md");
        write_atomic(&target, "hello\n").unwrap();
        assert_eq!(std::fs::read_to_string(&target).unwrap(), "hello\n");
        let names: Vec<_> = std::fs::read_dir(target.parent().unwrap())
            .unwrap()
            .map(|e| e.unwrap().file_name().into_string().unwrap())
            .collect();
        assert_eq!(names, vec!["c.md"]);
        // Overwrite works too.
        write_atomic(&target, "again\n").unwrap();
        assert_eq!(std::fs::read_to_string(&target).unwrap(), "again\n");
    }

    /// Build a real repo with one commit on `main`, then a feature branch
    /// one commit ahead, and register it as a workspace with a recap, a
    /// status, and a primary agent. `gather` must reflect all of it and
    /// tolerate the missing transcript.
    #[tokio::test]
    async fn gather_reads_store_git_and_tolerates_missing_transcript() {
        use crate::data::store::{NewWorkspace, Store};
        use std::process::Command;

        let repo = tempfile::TempDir::new().unwrap();
        let git = |args: &[&str]| {
            let st = Command::new("git")
                .current_dir(repo.path())
                .args(args)
                .status()
                .unwrap();
            assert!(st.success(), "git {args:?}");
        };
        git(&["init", "-q", "-b", "main"]);
        git(&["config", "user.email", "t@example.com"]);
        git(&["config", "user.name", "T"]);
        git(&["commit", "--allow-empty", "-q", "-m", "init"]);
        git(&["checkout", "-q", "-b", "feat/x"]);
        git(&["commit", "--allow-empty", "-q", "-m", "do the thing"]);
        std::fs::write(repo.path().join("scratch.txt"), "x").unwrap();

        let store = Store::open_in_memory().unwrap();
        let repo_id = store.add_repo(repo.path(), "myrepo", "feat").unwrap();
        let ws_id = store
            .insert_workspace(&NewWorkspace {
                repo_id,
                name: "x",
                branch: "feat/x",
                worktree_path: repo.path(),
                yolo: false,
                agent: AgentKind::Claude,
                shared: false,
            })
            .unwrap();
        store
            .add_primary_agent(ws_id, AgentKind::Claude, 0)
            .unwrap();
        store.add_workspace_agent(ws_id, AgentKind::Codex).unwrap();
        store
            .set_workspace_recap(ws_id, Some("ship x"), None, Some("tests"), None, None, None)
            .unwrap();
        store
            .set_workspace_status(ws_id, ReportedState::Working, Some("on it"), "claude")
            .unwrap();
        let ws = store.workspace_by_id(ws_id).unwrap().unwrap();

        let d = gather(&store, &ws).await.unwrap();
        assert_eq!(d.repo_name, "myrepo");
        assert_eq!(d.workspace_name, "x");
        assert_eq!(d.branch, "feat/x");
        assert_eq!(d.base_ref, "main"); // no origin → fallback
        assert_eq!(d.worktree, repo.path());
        let labels: Vec<_> = d.agents.iter().map(|a| a.label()).collect();
        assert_eq!(labels, vec!["claude", "codex"]);
        assert!(d.agents[0].is_primary);
        assert_eq!(d.status.as_ref().unwrap().message.as_deref(), Some("on it"));
        assert_eq!(d.recap.as_ref().unwrap().goal.as_deref(), Some("ship x"));
        assert_eq!(d.commits.len(), 1);
        assert!(d.commits[0].ends_with(" do the thing"));
        assert_eq!(d.uncommitted.unwrap().untracked, 1);
        assert!(d.last_assistant_text.is_none());
        assert!(d.now_ms > 0);
    }

    /// A worktree that no longer exists on disk must still produce a
    /// digest from the store alone.
    #[tokio::test]
    async fn gather_survives_missing_worktree() {
        use crate::data::store::{NewWorkspace, Store};
        let store = Store::open_in_memory().unwrap();
        let repo_id = store.add_repo(Path::new("/tmp/nope"), "r", "").unwrap();
        let ws_id = store
            .insert_workspace(&NewWorkspace {
                repo_id,
                name: "w",
                branch: "b/w",
                worktree_path: Path::new("/nonexistent/wsx-test/wt"),
                yolo: false,
                agent: AgentKind::Pi,
                shared: false,
            })
            .unwrap();
        let ws = store.workspace_by_id(ws_id).unwrap().unwrap();
        let d = gather(&store, &ws).await.unwrap();
        assert!(d.commits.is_empty());
        assert!(d.uncommitted.is_none());
        assert!(d.last_assistant_text.is_none());
        assert!(d.agents.is_empty());
        assert!(d.status.is_none());
        assert!(d.recap.is_none());
        let out = render(&d);
        assert!(out.contains("- agents: -\n"));
    }
}
